CREATE TABLE IF NOT EXISTS LOCATION (
ID bigserial PRIMARY KEY NOT NULL,
PARCEL_ID INT references PARCEL(ID)  NOT NULL,
NAME TEXT NOT NULL,
CREATEDBY TEXT NOT NULL,
CREATEDON timestamp  with time zone NOT NULL,
UPDATEDBY TEXT,
UPDATEDON timestamp  with time zone
);
